(function(){
'use strict';
const S=window.Savanski,st=S.state,C=window.SAVANSKI_BACKEND;
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('SavanskiArtStudio',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('projects'))d.createObjectStore('projects',{keyPath:'id'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbPut(store,val,key){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(store,'readwrite'),s=tx.objectStore(store);key===undefined?s.put(val):s.put(val,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function idbGet(store,key){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbAll(store){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
S.serializeProject=function(){const p=st.project;if(!p)return null;S.syncAnimationProject?.();const out={format:p.format,version:S.VERSION,id:p.id,name:p.name,width:p.width,height:p.height,transparent:p.transparent,background:p.background,createdAt:p.createdAt,updatedAt:new Date().toISOString(),map:{...st.map},animation:{frames:st.animation.frames,fps:st.animation.fps,keyframes:structuredClone(st.animation.keyframes)},meta:{...(p.meta||{}),app:'Savanski Art Studio'},layers:p.layers.map(l=>({id:l.id,name:l.name,visible:l.visible,locked:l.locked,opacity:l.opacity,blend:l.blend,kind:l.kind,meta:l.meta||{},dataUrl:l.canvas.toDataURL('image/png')}))};p.updatedAt=out.updatedAt;return out};
S.loadSerializedProject=async function(data){if(!data||data.format!=='savanski-art-studio'||!Array.isArray(data.layers))throw new Error('Not a Savanski project file.');const p=S.makeProject(+data.width||1600,+data.height||900,data.name||'Untitled Project');Object.assign(p,{id:data.id||p.id,transparent:data.transparent!==false,background:data.background||'#F2FFFF',createdAt:data.createdAt||p.createdAt,updatedAt:data.updatedAt||new Date().toISOString(),meta:data.meta||{}});p.layers=[];st.project=p;st.map={...st.map,...(data.map||{})};st.animation={frame:0,frames:data.animation?.frames||90,fps:data.animation?.fps||30,keyframes:data.animation?.keyframes||{},playing:false,stop:false};S.resizeViewCanvases();for(const src of data.layers){const c=document.createElement('canvas');c.width=p.width;c.height=p.height;const ctx=c.getContext('2d',{willReadFrequently:true}),l={id:src.id||S.uid('layer'),name:src.name||'Layer',visible:src.visible!==false,locked:!!src.locked,opacity:src.opacity??1,blend:src.blend||'source-over',kind:src.kind||'raster',meta:src.meta||{},canvas:c,ctx};p.layers.push(l);if(src.dataUrl){try{const im=await S.loadImage(src.dataUrl);ctx.drawImage(im,0,0)}catch(e){console.warn('Layer image failed',src.name,e)}}}if(!p.layers.length)S.newLayer('Artwork');st.activeLayerId=p.layers.at(-1).id;S.renderLayers();S.renderLayerList();S.syncProjectUI?.();S.syncMapUI?.();S.syncAnimationUI?.();S.fitCanvas();return p};
S.saveBrowser=async function(){if(!st.project)return;try{const data=S.serializeProject();await idbPut('projects',data);await idbPut('meta',data.id,'lastProject');localStorage.setItem('savanski.lastProjectId',data.id);S.toast('Saved in this browser','success')}catch(e){console.error(e);S.toast('Browser save failed. Download the project file instead.','error')}};
S.loadBrowser=async function(id=null){try{id=id||localStorage.getItem('savanski.lastProjectId')||await idbGet('meta','lastProject');if(!id)return false;const data=await idbGet('projects',id);if(!data)return false;await S.loadSerializedProject(data);S.toast('Local project opened','success');return true}catch(e){console.error(e);return false}};
S.listBrowserProjects=()=>idbAll('projects');
S.autosave=S.debounce(async()=>{if(!st.settings.autosave||!st.project)return;try{const data=S.serializeProject();await idbPut('projects',data);await idbPut('meta',data.id,'lastProject');localStorage.setItem('savanski.lastProjectId',data.id)}catch(e){console.debug('Autosave skipped',e)}},900);
S.downloadProject=function(){const data=S.serializeProject(),blob=new Blob([JSON.stringify(data)],{type:'application/json'});S.downloadBlob(blob,S.safeName(st.project.name,'.savanski.json'));S.toast('Editable project downloaded','success')};
S.openProjectFile=async function(file){const text=await file.text();const data=JSON.parse(text);await S.loadSerializedProject(data);S.toast(`Opened ${file.name}`,'success')};
function jsonp(url){return new Promise((resolve,reject)=>{const cb='__savanski_cb_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>{cleanup();reject(new Error('Service request timed out.'))},20000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};s.onerror=()=>{cleanup();reject(new Error('Service request failed.'))};s.src=url+(url.includes('?')?'&':'?')+'callback='+encodeURIComponent(cb);document.head.append(s)})}
S.apiGet=async function(action,params={},baseUrl=C.serviceUrl){const u=new URL(baseUrl);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null)u.searchParams.set(k,String(v));try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){return jsonp(u.toString())}};
S.apiPost=async function(body,baseUrl=C.serviceUrl){try{const r=await fetch(baseUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){console.warn('Readable POST failed',e);try{await fetch(baseUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});return{ok:true,opaque:true}}catch(e2){throw e2}}};
S.refreshStorage=async function(){S.status('Checking storage…');let personal=null;try{personal=await S.apiGet('storageStatus',{mode:'personal'},C.personalConnectorUrl||C.serviceUrl)}catch{}if(personal?.ok){st.driveMode='personal';S.$('#storagePill').textContent=`Google Drive · ${personal.folderName||'connected'}`;S.toast('Personal Google Drive is connected','success');return personal}st.driveMode='shared';let shared;try{shared=await S.apiGet('storageStatus',{mode:'shared',clientKey:S.getClientKey()})}catch(e){S.$('#storagePill').textContent='Local workspace';throw e}S.$('#storagePill').textContent=shared?.ok?'Shared fallback storage':'Local workspace';return shared};
S.connectDrive=function(){const u=new URL(C.personalConnectorUrl||C.serviceUrl);u.searchParams.set('action','connect');window.open(u.toString(),'savanskiDriveConnect','width=720,height=720,noopener,noreferrer');S.toast('Google Drive authorization opened. Refresh storage after it finishes.')};
S.saveProjectDrive=async function(){const data=S.serializeProject(),text=JSON.stringify(data);if(text.length>45*1024*1024){S.toast('This project is too large for a single service request. Download it locally or connect Drive and split large source images into separate files.','error');return}S.status('Saving through Google Drive…');const body={action:'saveProject',title:data.name,project:data,storageMode:st.driveMode,clientKey:S.getClientKey()};const r=await S.apiPost(body,st.driveMode==='personal'?(C.personalConnectorUrl||C.serviceUrl):C.serviceUrl);if(r?.ok){S.$('#storagePill').textContent=st.driveMode==='personal'?'Google Drive connected':'Shared fallback storage';S.toast(r.opaque?'Save request sent':'Saved through Google Drive','success')}else S.toast(r?.error||'Drive save failed.','error')};
S.saveBlobDrive=async function(blob,filename,category='exports'){if(blob.size>C.maxInlineBytes){S.toast('This export is over the inline cloud limit. Download it locally or place it in Drive directly.','error');return null}const b64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob)});return S.apiPost({action:'saveBinary',filename,category,mimeType:blob.type||'application/octet-stream',base64:b64,storageMode:st.driveMode,clientKey:S.getClientKey()},st.driveMode==='personal'?(C.personalConnectorUrl||C.serviceUrl):C.serviceUrl)};
})();
