(function(root){'use strict';
const A=root.AIBrain=root.AIBrain||{};const ORDER={private:0,project:1,series:2,universe:3,workspace:3,global:4};
function resolve({workspaceId=null,userId=null,projectId=null,universeId=null,seriesId=null,requestedScope='project',allowShared=false,permissions={}}={}){const allowed=new Set(['global']);if(workspaceId)allowed.add(`workspace:${workspaceId}`);if(userId&&permissions.user!==false)allowed.add(`user:${userId}`);if(projectId)allowed.add(`project:${projectId}`);if(allowShared&&universeId)allowed.add(`universe:${universeId}`);if(allowShared&&seriesId)allowed.add(`series:${seriesId}`);return{requestedScope,allowed:[...allowed],permissions,privateDataRule:'Private user/project data never becomes global corpus knowledge.',canonRule:'Conflicts are surfaced; no silent canon mutation.'};}
function mayRead(recordScope,currentScope='project',permissions={}){if(!recordScope||recordScope==='global')return true;if(recordScope==='private')return!!permissions.private;if(recordScope.includes(':'))return true;return (ORDER[recordScope]??1)>=(ORDER[currentScope]??1)||recordScope===currentScope;}
function permits(record,scope){const s=record?.scope||'global';if(s==='global')return true;if(scope?.allowed?.includes(s))return true;return mayRead(s,scope?.requestedScope||'project',scope?.permissions||{});}
function filter(records,ctx={}){const scope=ctx.allowed?ctx:resolve(ctx);return(records||[]).filter(r=>!ctx.projectId||!r.projectId||r.projectId===ctx.projectId).filter(r=>permits(r,scope));}
A.projectScope=function(project,request){if(!project)return{project:null,allowed:[],warning:'No project context supplied.'};const allowedFields=['id','name','summary','status','priority','tags','paths','dependencies','notes','canon','timeline','rules','permissions','fileIds','domains','type'];const scoped={};for(const k of allowedFields)if(project[k]!==undefined)scoped[k]=project[k];return{project:scoped,allowed:allowedFields,request,rule:'Do not import private facts from unrelated projects; global knowledge is not personal/project truth.'};};
const API={resolve,mayRead,permits,filter};root.AIBrainProjectScope=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
