/* Genericized for AI-Brain capability use. Provenance group: active-session-runtime-c. */
(function(){
  'use strict';
  const U=window.PZUtils,C=window.ActiveWorkspace_CONFIG;
  const Dice={};
  const TOKEN=/([+-]?\s*(?:\d*d(?:%|\d+)(?:(?:kh|kl|dh|dl)\d+)?|\d+))/ig;
  function secureDie(sides){return U.randomInt(1,Math.max(2,U.int(sides,20)))}
  function parseTerm(raw){const sign=String(raw).trim().startsWith('-')?-1:1,body=String(raw).replace(/^[+\-]\s*/,'').replace(/\s+/g,'');const m=body.match(/^(\d*)d(%|\d+)(?:(kh|kl|dh|dl)(\d+))?$/i);if(!m)return{kind:'flat',sign,value:U.int(body,0),raw};const count=U.clamp(U.int(m[1]||1),1,100),sides=m[2]==='%'?100:U.clamp(U.int(m[2]),2,1000),op=(m[3]||'').toLowerCase(),n=U.clamp(U.int(m[4]||count),1,count);let keepMode='',keepCount=count;if(op==='kh'){keepMode='h';keepCount=n}else if(op==='kl'){keepMode='l';keepCount=n}else if(op==='dh'){keepMode='l';keepCount=Math.max(1,count-n)}else if(op==='dl'){keepMode='h';keepCount=Math.max(1,count-n)}return{kind:'dice',sign,count,sides,keepMode,keepCount,raw}}
  Dice.command=text=>{let s=String(text||'').trim().replace(/[“”]/g,'"').replace(/[‘’]/g,"'");if(/\binitiative\b/i.test(s)){const mod=(s.replace(/\s+/g,'').match(/([+-]\d+)$/)||['',''])[1];return`1d20${mod}`}s=s.replace(/^\s*(?:\/roll|roll|please roll|can you roll|could you roll)\s+/i,'');const m=s.match(/(?:\d*d(?:%|\d+)(?:(?:kh|kl|dh|dl)\d+)?)(?:\s*[+\-]\s*(?:\d*d(?:%|\d+)(?:(?:kh|kl|dh|dl)\d+)?|\d+))*/i);return m?m[0].replace(/\s+/g,''):(/^[-+]?\d+$/.test(s)?s:'1d20')};
  Dice.parse=expression=>{let source=String(expression||'').toLowerCase().replace(/advantage/g,'adv').replace(/disadvantage/g,'dis').trim();const mode=/\bdis\b/.test(source)?'disadvantage':/\badv\b/.test(source)?'advantage':'normal';source=source.replace(/\b(?:adv|dis)\b/g,'');const terms=(source.match(TOKEN)||[]).map(parseTerm);if(!terms.length)throw new Error('Use notation such as 1d20+5, 2d6+3, 4d6kh3, or a command such as roll initiative +4.');return{expression:String(expression).trim(),mode,terms}}
  function rollParsed(parsed,options={}){const all=[];let total=0;for(const term of parsed.terms){if(term.kind==='flat'){total+=term.sign*term.value;all.push({...term,total:term.sign*term.value});continue}let count=term.count,keepMode=term.keepMode,keepCount=term.keepCount;if(parsed.mode!=='normal'&&term.sides===20&&term.count===1){count=2;keepMode=parsed.mode==='advantage'?'h':'l';keepCount=1}const values=Array.from({length:count},()=>secureDie(term.sides)),indexed=values.map((value,index)=>({value,index}));indexed.sort((a,b)=>keepMode==='l'?a.value-b.value:b.value-a.value);const keptIndexes=new Set((keepMode?indexed.slice(0,keepCount):indexed).map(x=>x.index)),subtotal=values.reduce((s,v,i)=>s+(keptIndexes.has(i)?v:0),0)*term.sign;total+=subtotal;all.push({...term,count,values,keptIndexes:[...keptIndexes],subtotal})}const d20=all.find(t=>t.kind==='dice'&&t.sides===20),keptD20=d20?d20.values.filter((_,i)=>d20.keptIndexes.includes(i))[0]:null;return{id:U.uid(options.hostile?'hostile-roll':'roll'),expression:parsed.expression,mode:parsed.mode,total,terms:all,natural:keptD20,critical:keptD20===20,fumble:keptD20===1,createdAt:U.now(),channel:options.hostile?'hostile':'player'}}
  Dice.roll=(expression,options={})=>rollParsed(Dice.parse(expression),options);
  Dice.netEdge=(edge=0,burden=0)=>U.clamp(U.int(edge)-U.int(burden),-2,2);
  Dice.testExpression=({abilityModifier=0,proficiencyBonus=0,trained=false,modifier=0,edge=0,burden=0}={})=>{const net=Dice.netEdge(edge,burden),count=1+Math.abs(net),keep=net>0?`kh1`:net<0?`kl1`:'';const mod=U.int(abilityModifier)+U.int(modifier)+(trained?U.int(proficiencyBonus):0);return`${count}d20${keep}${mod>=0?'+':''}${mod}`};
  Dice.outcome=(roll,dc)=>{dc=U.int(dc,12);if(roll.natural===20||roll.total>=dc+10)return{id:'breakthrough',name:'Breakthrough',description:'Success with major added effect or advantage.'};if(roll.total>=dc)return{id:'clean_success',name:'Clean Success',description:'The stated intent succeeds without the threatened cost.'};if(roll.total>=dc-4)return{id:'costly_opening',name:'Costly Opening',description:'The player may accept the stated cost to succeed, or decline and face a setback.'};if(roll.total>=dc-9)return{id:'setback',name:'Setback',description:'The intent does not fully succeed and the established risk follows.'};return{id:'crisis',name:'Crisis',description:'A severe consequence follows from the established risk.'}}
  Dice.rollTest=opts=>{const expression=Dice.testExpression(opts),roll=Dice.roll(expression,opts);return{...roll,dc:U.int(opts.dc,12),outcome:Dice.outcome(roll,opts.dc)}};
  Dice.rollInitiative=(bonus=0,options={})=>Dice.roll(`1d20${Number(bonus)>=0?'+':''}${U.int(bonus)}`,options);
  Dice.describe=roll=>roll.terms.map(t=>t.kind==='flat'?`${t.sign<0?'-':'+'}${Math.abs(t.value)}`:`${t.count}d${t.sides} [${t.values.map((v,i)=>t.keptIndexes.includes(i)?v:`(${v})`).join(', ')}]`).join(' ')+` = ${roll.total}`;
  Dice.personas=()=>{const rows=window.DICE_BOT_PERSONAS||[];if(Array.isArray(rows)&&rows.length)return rows.map(x=>({id:x.id,name:x.name,meta:x,responseCount:0}));return Object.entries(window.DICE_BOT_RESPONSE_BANKS||{}).map(([id,v])=>({id,name:v.meta?.name||id,meta:v.meta||{},responseCount:v.responseCount||0}))};
  Dice.personaLine=(personaId,intent='roll_result',vars={})=>{const p=(window.DICE_BOT_RESPONSE_BANKS||{})[personaId];if(!p)return'';const banks=p.intents||{},arr=banks[intent]||banks.roll_result||banks.roll_start||[];let line=U.pick(arr)||'';Object.entries(vars).forEach(([k,v])=>line=line.replaceAll(`{${k}}`,String(v)));return line};
  Dice.canonReply=(message,personaId='')=>{const persona=(window.DICE_BOT_PERSONAS||[]).find(x=>x.id===personaId)||(window.DICE_BOT_PERSONAS||[])[0]||{};const result=window.DiceBotCanon?.detect?.(message,persona);return result?.html||''};
  Dice.loadTheme=themeFile=>{let link=document.getElementById('diceThemeLink');if(!link){link=document.createElement('link');link.id='diceThemeLink';link.rel='stylesheet';document.head.appendChild(link)}link.href=`css/dice-themes/${String(themeFile).replace(/[^a-zA-Z0-9._-]/g,'')}`};
  Dice.visualize=roll=>window.ActiveWorkspaceDice3D?.visualize?.(roll)||Promise.resolve();
  Dice.recordPlayer=async({expression,label='',characterId='',encounterId='',kind='general',privateRoll=false,dc=null,test=null})=>{const api=window.ActiveWorkspaceAPI,user=api.requireAuth(),roll=test?Dice.rollTest(test):Dice.roll(expression),record={...roll,label:U.safeText(label),kind,private:!!privateRoll,actorType:'player',actorId:characterId||user.id,actorName:user.displayName,userId:user.id,encounterId};if(dc!=null&&!record.outcome){record.dc=U.int(dc);record.outcome=Dice.outcome(record,dc)}try{await api.call('rollRecord',{roll:record})}catch(err){console.warn('Roll sync failed',err)}U.emit('roll-recorded',record);Dice.visualize(record);return record};
  Dice.rollHostile=({expression,label='',hostile,encounterId='',kind='attack',dc=null})=>{const roll=Dice.roll(expression,{hostile:true}),record={...roll,label,kind,private:false,actorType:'hostile',actorId:hostile.id,actorName:hostile.name,encounterId};if(dc!=null){record.dc=U.int(dc);record.outcome=Dice.outcome(record,dc)}Dice.visualize(record);return record};
  window.ActiveWorkspaceDice=Object.freeze(Dice);
})();
